export const skills = [
  {
    id: 1,
    imgUrl: './logo/angular-seeklogo.com.svg',
    profieciency: '40%',
  },
  {
    id: 2,
    imgUrl: './logo/vuejs-icon.svg',
    profieciency: '51%',
  },
  {
    id: 3,
    imgUrl: './logo/react-seeklogo.com.svg',
    profieciency: '88%',
  },
  {
    id: 4,
    imgUrl: './logo/typescriptlang-icon.svg',
    profieciency: '67%',
  },
  {
    id: 5,
    imgUrl: './logo/nodejs-icon.svg',
    profieciency: '82%',
  },
  {
    id: 6,
    imgUrl: './logo/mongodb-icon.svg',
    profieciency: '60%',
  },
  {
    id: 7,
    imgUrl: './logo/tailwind-css-seeklogo.com.svg',
    profieciency: '94%',
  },
  {
    id: 8,
    imgUrl: './logo/material-ui-1.svg',
    profieciency: '71%',
  },
  {
    id: 9,
    imgUrl: './logo/redux.svg',
    profieciency: '88%',
  },
  {
    id: 10,
    imgUrl: './logo/nextjs.svg',
    profieciency: '63%',
  },
  {
    id: 11,
    imgUrl: './logo/javascript.svg',
    profieciency: '90%',
  },
  {
    id: 12,
    imgUrl: './logo/html5.svg',
    profieciency: '90%',
  },
  {
    id: 13,
    imgUrl: './logo/css-3.svg',
    profieciency: '96%',
  },
  {
    id: 14,
    imgUrl: './logo/mysql-6.svg',
    profieciency: '45%',
  },
  {
    id: 15,
    imgUrl: './logo/php-1.svg',
    profieciency: '48%',
  },
];

export const projects = [
  {
    id: 1,
    src: "./img/music-hubs.png",
    title: "Music Hubs",
    github: "https://github.com/rosanno/music-hubs",
    url: "https://musical-pixie-d19449.netlify.app/",
    techStacks: [
      "./logo/react-seeklogo.com.svg",
      "./logo/redux-seeklogo.com.svg",
      "./logo/shazam.png",
      "./logo/tailwind-css-seeklogo.com.svg",
    ],
    desc: "An enteratinment web application for those who loves to listen music. This application have play, repeat, skip, and shuffle music functionality",
  },
  {
    id: 2,
    src: "./img/earsockets.png",
    title: "Earsockets MERN STACK",
    github: "https://github.com/rosanno/earsockets-mernstack",
    url: "https://earsockets-client.onrender.com/",
    techStacks: [
      "./logo/react-seeklogo.com.svg",
      "./logo/redux-seeklogo.com.svg",
      "./logo/nodejs-icon.svg",
      "./logo/expressjs-ar21.svg",
      "./logo/mongodb-icon.svg",
      "./logo/material-ui-1.svg",
    ],
    desc: " Earsockets it's a basic online shop where a registered user can checkout, add products to cart, update quantity in the cart and pay orders through a Stripe api.",
  },
  {
    id: 3,
    src: "./img/movie.png",
    title: "React Movie",
    github: "https://github.com/rosanno/react-movie",
    url: "",
    techStacks: [
      "./logo/react-seeklogo.com.svg",
      "./logo/next-js-seeklogo.com.svg",
      "./logo/typescriptlang-icon.svg",
      "./logo/tailwind-css-seeklogo.com.svg",
    ],
    desc: "Entertainment web app for those who love watching movies. This is build using TMDB API.",
  },
  {
    id: 4,
    src: "./img/food_truck.png",
    title: "Food Truck Website",
    url: "",
    techStacks: [
      "./logo/angular-seeklogo.com.svg",
      "./logo/typescriptlang-icon.svg",
      "./logo/nodejs-icon.svg",
      "./logo/expressjs-ar21.svg",
      "./logo/mongodb-icon.svg",
      "./logo/tailwind-css-seeklogo.com.svg",
    ],
    desc: "Fullstack website for ordering food.Features user can register/login, add food cart, pay order food using paypal payment api, track food order and select user location using leaflet map integration.",
  },
  {
    id: 5,
    src: "./img/chat-app.png",
    title: "Mern Chat",
    url: "https://chats-client.onrender.com/",
    techStacks: [
      "./logo/react-seeklogo.com.svg",
      "./logo/nodejs-icon.svg",
      "./logo/expressjs-ar21.svg",
      "./logo/mongodb-icon.svg",
      "./logo/socketio-icon.svg",
      "./logo/tailwind-css-seeklogo.com.svg",
    ],
    desc: "MERN web app using react, nodejs, express and socket.io. The features of this app user can see offline online status of another user, push notifications, chat rooms, and realtime chat messages.",
  },
  {
    id: 6,
    src: "./img/weather.png",
    title: "Weather app",
    url: "https://thelocalweathers.netlify.app/",
    techStacks: [
      "./logo/vuejs-icon.svg",
      "./logo/tailwind-css-seeklogo.com.svg",
    ],
    desc: "A web app that display the current weather in your area and hourly forecast weather. This app is power by openweathermap api.",
  },
];
